### ISSUE TITLE
can't run the script on osx 10.13.2

### ISSUE THREAD

**Issue by deadbaed** [tardypad/github-jack#1]
hi, i just cloned the repo and tried to run it, but apparently i can't, do you know what's the issue?

thanks

screenshot provided 
![screen shot 2018-06-24 at 11 18 47](https://user-images.githubusercontent.com/8809909/41817696-7f53c664-77a0-11e8-873a-308ba230b387.png)

**Comment by tardypad** [comment]
This is most likely a problem with your OSX version of bash
I believe your readlink doesn't support the `--canonicalize` option defined there: https://github.com/tardypad/github-jack/blob/master/gh-jack#L10
That's what the error line `usage: readline [-n] [file ...]` suggests

This kind of issue often happens with OSX and this tool is unfortunately no POSIX compliant.
So there might be a few places you'd need to update to make it work on your machine.
Or you'd need to install the GNU version of bash I guess

**Comment by deadbaed** [comment]
i see, that's weird cause i actually use zsh....

thanks anyway, imma just do that under my linux install.

**Comment by tardypad** [comment]
But the script is actually using bash
https://github.com/tardypad/github-jack/blob/56df7142dd6ffca7d0cd2f0b05df66ebcb3513c7/gh-jack#L1

**Comment by deadbaed** [comment]
oh okay, didn't realize that.

well i think something's wrong in osx, ha
